### PR TITLE
change lein download url

### PR DESCRIPTION
**Pull request by SimY4**

### CODE REVIEW

**Comment by winks** [comment]
Hi,
good catch - but I think we should keep `$version` and not `stable` - people will hardly ever use this as it is, but install via chocolatey, so there the new version is set anyway.

**Comment by SimY4** [comment]
Hi, @winks 

Thanks for pointing that out. I've added back the version into download url.

**Comment by SimY4** [comment]
Hi, @winks 

Can you please promote these changes into chocolatey repo?

**Comment by winks** [comment]
@SimY4 Are there some real problems while trying to install? 
When I tested the latest release, it worked. So my original plan was to incorporate this into the next release.

**Comment by SimY4** [comment]
@winks yes, there is. I can't install leaningen via chocolatey. There's an issue with Content-length mismatch problem described on Lein package page. And the package is marked as failing since July 2017

**Comment by winks** [comment]
@SimY4 
I do remember that I tried to reproduce that build error and couldn't. Might as well be that Github changed something this summer, maybe how they redirect...
As you can see we've only released 2.7 via chocolatey once in December, and it did work back then.

I'll see what I can do to get a new release of 2.7.1 running over there.

**Comment by SimY4** [comment]
@winks Thank you. Tell me if you need any help, I can check wether it works.

**Comment by winks** [comment]
@SimY4 I've pushed an update, but it needs to be moderated, so https://chocolatey.org/packages/Lein/2.7.1.20170913 is maybe invisible to you.

Ping me in a few days if it didn't go live, or if it did and didn't work. I just tried installing on Win7 and it worked.

**Comment by winks** [comment]
After some hiccups it's released now: https://chocolatey.org/packages/lein

**Comment by SimY4** [comment]
@winks updated jdk dependency is a great bonus. 😀 Thank you!

**Pull request merged**
